[{
	"resource": "/home/walterlan/Documentos/poker-game/frontend/src/App.jsx",
	"owner": "eslint2",
	"severity": 8,
	"message": "Parsing error: Unexpected token App",
	"source": "eslint",
	"startLineNumber": 378,
	"startColumn": 7,
	"endLineNumber": 378,
	"endColumn": 7,
	"modelVersionId": 86,
	"origin": "extHost1"
},{
	"resource": "/home/walterlan/Documentos/poker-game/frontend/src/App.jsx",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "';' esperado.",
	"source": "ts",
	"startLineNumber": 378,
	"startColumn": 7,
	"endLineNumber": 378,
	"endColumn": 10,
	"modelVersionId": 86,
	"origin": "extHost1"
},{
	"resource": "/home/walterlan/Documentos/poker-game/frontend/src/App.jsx",
	"owner": "typescript",
	"code": "1127",
	"severity": 8,
	"message": "Caractere inválido.",
	"source": "ts",
	"startLineNumber": 378,
	"startColumn": 17,
	"endLineNumber": 378,
	"endColumn": 18,
	"modelVersionId": 86,
	"origin": "extHost1"
},{
	"resource": "/home/walterlan/Documentos/poker-game/frontend/src/App.jsx",
	"owner": "typescript",
	"code": "1434",
	"severity": 8,
	"message": "Palavra-chave ou identificador inesperado.",
	"source": "ts",
	"startLineNumber": 378,
	"startColumn": 19,
	"endLineNumber": 378,
	"endColumn": 27,
	"modelVersionId": 86,
	"origin": "extHost1"
},{
	"resource": "/home/walterlan/Documentos/poker-game/frontend/src/App.jsx",
	"owner": "typescript",
	"code": "1434",
	"severity": 8,
	"message": "Palavra-chave ou identificador inesperado.",
	"source": "ts",
	"startLineNumber": 378,
	"startColumn": 28,
	"endLineNumber": 378,
	"endColumn": 34,
	"modelVersionId": 86,
	"origin": "extHost1"
},{
	"resource": "/home/walterlan/Documentos/poker-game/frontend/src/App.jsx",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "';' esperado.",
	"source": "ts",
	"startLineNumber": 379,
	"startColumn": 7,
	"endLineNumber": 379,
	"endColumn": 10,
	"modelVersionId": 86,
	"origin": "extHost1"
},{
	"resource": "/home/walterlan/Documentos/poker-game/frontend/src/App.jsx",
	"owner": "typescript",
	"code": "1127",
	"severity": 8,
	"message": "Caractere inválido.",
	"source": "ts",
	"startLineNumber": 379,
	"startColumn": 18,
	"endLineNumber": 379,
	"endColumn": 19,
	"modelVersionId": 86,
	"origin": "extHost1"
},{
	"resource": "/home/walterlan/Documentos/poker-game/frontend/src/App.jsx",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "';' esperado.",
	"source": "ts",
	"startLineNumber": 380,
	"startColumn": 7,
	"endLineNumber": 380,
	"endColumn": 10,
	"modelVersionId": 86,
	"origin": "extHost1"
},{
	"resource": "/home/walterlan/Documentos/poker-game/frontend/src/App.jsx",
	"owner": "typescript",
	"code": "1127",
	"severity": 8,
	"message": "Caractere inválido.",
	"source": "ts",
	"startLineNumber": 380,
	"startColumn": 18,
	"endLineNumber": 380,
	"endColumn": 19,
	"modelVersionId": 86,
	"origin": "extHost1"
},{
	"resource": "/home/walterlan/Documentos/poker-game/frontend/src/App.jsx",
	"owner": "typescript",
	"code": "1434",
	"severity": 8,
	"message": "Palavra-chave ou identificador inesperado.",
	"source": "ts",
	"startLineNumber": 380,
	"startColumn": 20,
	"endLineNumber": 380,
	"endColumn": 25,
	"modelVersionId": 86,
	"origin": "extHost1"
},{
	"resource": "/home/walterlan/Documentos/poker-game/frontend/src/App.jsx",
	"owner": "typescript",
	"code": "1434",
	"severity": 8,
	"message": "Palavra-chave ou identificador inesperado.",
	"source": "ts",
	"startLineNumber": 380,
	"startColumn": 26,
	"endLineNumber": 380,
	"endColumn": 32,
	"modelVersionId": 86,
	"origin": "extHost1"
},{
	"resource": "/home/walterlan/Documentos/poker-game/frontend/src/App.jsx",
	"owner": "typescript",
	"code": "1127",
	"severity": 8,
	"message": "Caractere inválido.",
	"source": "ts",
	"startLineNumber": 380,
	"startColumn": 43,
	"endLineNumber": 380,
	"endColumn": 44,
	"modelVersionId": 86,
	"origin": "extHost1"
},{
	"resource": "/home/walterlan/Documentos/poker-game/frontend/src/App.jsx",
	"owner": "typescript",
	"code": "1434",
	"severity": 8,
	"message": "Palavra-chave ou identificador inesperado.",
	"source": "ts",
	"startLineNumber": 380,
	"startColumn": 45,
	"endLineNumber": 380,
	"endColumn": 52,
	"modelVersionId": 86,
	"origin": "extHost1"
},{
	"resource": "/home/walterlan/Documentos/poker-game/frontend/src/App.jsx",
	"owner": "typescript",
	"code": "1127",
	"severity": 8,
	"message": "Caractere inválido.",
	"source": "ts",
	"startLineNumber": 380,
	"startColumn": 63,
	"endLineNumber": 380,
	"endColumn": 64,
	"modelVersionId": 86,
	"origin": "extHost1"
},{
	"resource": "/home/walterlan/Documentos/poker-game/frontend/src/App.jsx",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "';' esperado.",
	"source": "ts",
	"startLineNumber": 381,
	"startColumn": 7,
	"endLineNumber": 381,
	"endColumn": 14,
	"modelVersionId": 86,
	"origin": "extHost1"
},{
	"resource": "/home/walterlan/Documentos/poker-game/frontend/src/App.jsx",
	"owner": "typescript",
	"code": "1434",
	"severity": 8,
	"message": "Palavra-chave ou identificador inesperado.",
	"source": "ts",
	"startLineNumber": 381,
	"startColumn": 15,
	"endLineNumber": 381,
	"endColumn": 20,
	"modelVersionId": 86,
	"origin": "extHost1"
},{
	"resource": "/home/walterlan/Documentos/poker-game/frontend/src/App.jsx",
	"owner": "typescript",
	"code": "1434",
	"severity": 8,
	"message": "Palavra-chave ou identificador inesperado.",
	"source": "ts",
	"startLineNumber": 381,
	"startColumn": 21,
	"endLineNumber": 381,
	"endColumn": 23,
	"modelVersionId": 86,
	"origin": "extHost1"
},{
	"resource": "/home/walterlan/Documentos/poker-game/frontend/src/App.jsx",
	"owner": "typescript",
	"code": "1127",
	"severity": 8,
	"message": "Caractere inválido.",
	"source": "ts",
	"startLineNumber": 381,
	"startColumn": 29,
	"endLineNumber": 381,
	"endColumn": 30,
	"modelVersionId": 86,
	"origin": "extHost1"
},{
	"resource": "/home/walterlan/Documentos/poker-game/frontend/src/App.jsx",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "';' esperado.",
	"source": "ts",
	"startLineNumber": 382,
	"startColumn": 7,
	"endLineNumber": 382,
	"endColumn": 14,
	"modelVersionId": 86,
	"origin": "extHost1"
},{
	"resource": "/home/walterlan/Documentos/poker-game/frontend/src/App.jsx",
	"owner": "typescript",
	"code": "1434",
	"severity": 8,
	"message": "Palavra-chave ou identificador inesperado.",
	"source": "ts",
	"startLineNumber": 382,
	"startColumn": 15,
	"endLineNumber": 382,
	"endColumn": 18,
	"modelVersionId": 86,
	"origin": "extHost1"
},{
	"resource": "/home/walterlan/Documentos/poker-game/frontend/src/App.jsx",
	"owner": "typescript",
	"code": "1434",
	"severity": 8,
	"message": "Palavra-chave ou identificador inesperado.",
	"source": "ts",
	"startLineNumber": 382,
	"startColumn": 19,
	"endLineNumber": 382,
	"endColumn": 21,
	"modelVersionId": 86,
	"origin": "extHost1"
},{
	"resource": "/home/walterlan/Documentos/poker-game/frontend/src/App.jsx",
	"owner": "typescript",
	"code": "1127",
	"severity": 8,
	"message": "Caractere inválido.",
	"source": "ts",
	"startLineNumber": 382,
	"startColumn": 28,
	"endLineNumber": 382,
	"endColumn": 29,
	"modelVersionId": 86,
	"origin": "extHost1"
},{
	"resource": "/home/walterlan/Documentos/poker-game/frontend/src/App.jsx",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "';' esperado.",
	"source": "ts",
	"startLineNumber": 383,
	"startColumn": 7,
	"endLineNumber": 383,
	"endColumn": 14,
	"modelVersionId": 86,
	"origin": "extHost1"
},{
	"resource": "/home/walterlan/Documentos/poker-game/frontend/src/App.jsx",
	"owner": "typescript",
	"code": "1434",
	"severity": 8,
	"message": "Palavra-chave ou identificador inesperado.",
	"source": "ts",
	"startLineNumber": 383,
	"startColumn": 15,
	"endLineNumber": 383,
	"endColumn": 18,
	"modelVersionId": 86,
	"origin": "extHost1"
},{
	"resource": "/home/walterlan/Documentos/poker-game/frontend/src/App.jsx",
	"owner": "typescript",
	"code": "1127",
	"severity": 8,
	"message": "Caractere inválido.",
	"source": "ts",
	"startLineNumber": 383,
	"startColumn": 28,
	"endLineNumber": 383,
	"endColumn": 29,
	"modelVersionId": 86,
	"origin": "extHost1"
},{
	"resource": "/home/walterlan/Documentos/poker-game/frontend/src/App.jsx",
	"owner": "typescript",
	"code": "1185",
	"severity": 8,
	"message": "Marcador de conflito de mesclagem encontrado.",
	"source": "ts",
	"startLineNumber": 384,
	"startColumn": 1,
	"endLineNumber": 384,
	"endColumn": 8,
	"modelVersionId": 86,
	"origin": "extHost1"
}]  